export const APP_ROLES = [
  "customer",
  "employee",
  "admin",
  "super_admin",
] as const;

export const ROUTES = {
  home: "/",
  about: "/about",
  services: "/services",
  service: (slug: string) => `/services/${slug}`,
  schemes: "/schemes",
  scheme: (slug: string) => `/schemes/${slug}`,
  funding: "/funding",
  loans: "/loans",
  startupSupport: "/startup-support",
  blog: "/blog",
  post: (slug: string) => `/blog/${slug}`,
  faq: "/faq",
  testimonials: "/testimonials",
  caseStudies: "/case-studies",
  gallery: "/gallery",
  events: "/events",
  careers: "/careers",
  team: "/team",
  contact: "/contact",
  privacy: "/privacy-policy",
  terms: "/terms",
  refund: "/refund-policy",
  calculators: "/calculators",
  eligibility: "/tools/eligibility",
  recommendation: "/tools/recommendation",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  admin: "/admin",
} as const;
